"""empty message

Revision ID: 1b316f8d977d
Revises: c53a30d6ee3d
Create Date: 2023-10-04 12:09:11.936388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b316f8d977d'
down_revision = 'c53a30d6ee3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   op.add_column('lead', sa.Column('moverref', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lead')