"""create local lead table

Revision ID: ad8560f466d3
Revises: cd9d02b79341
Create Date: 2023-10-09 14:31:13.127193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad8560f466d3'
down_revision = 'cd9d02b79341'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('local_lead',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('label', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('firstname', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phone1', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ozip', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('dzip', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('dcity', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('dstate', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('movesize', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('movedte', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('conversion', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('validation', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sent_to_gronat', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sent_to_sheets', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('moverref', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='locallead_pkey')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('locallead')
    # ### end Alembic commands ###
