"""empty message

Revision ID: c53a30d6ee3d
Revises: 8c39be55d297
Create Date: 2023-09-28 15:35:18.009398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c53a30d6ee3d'
down_revision = '8c39be55d297'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # MoverrefConfig table
    op.create_table(
        'moverrefconfig',
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('name', sa.String, nullable=False),
        sa.Column('sequence_order', sa.Integer, nullable=False),
        sa.Column('repeat_count', sa.Integer, nullable=False)
    )

    # # SecondModel table
    # op.create_table(
    #    'moverrefconfig',
    #     sa.Column('id', sa.Integer, primary_key=True),
    #     sa.Column('name', sa.String, nullable=False),
    #     sa.Column('sequence_order', sa.Integer, nullable=False),
    #     sa.Column('repeat_count', sa.Integer, nullable=False)
    # )

    # Counter table
    op.create_table(
        'counter',
        sa.Column('id', sa.Integer, primary_key=True, autoincrement=True),
        sa.Column('moverref_count', sa.Integer, default=0)
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_table('moverrefconfig')
    op.drop_table('secondmodel')
    op.drop_table('counter')