"""add sheet range

Revision ID: cd9d02b79341
Revises: 57c25c8c0535
Create Date: 2023-10-06 13:53:40.015150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd9d02b79341'
down_revision = '57c25c8c0535'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
     op.add_column('domain', sa.Column('sheet_range', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('domain')