"""add sheet id

Revision ID: 57c25c8c0535
Revises: 1b316f8d977d
Create Date: 2023-10-06 12:26:55.926601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57c25c8c0535'
down_revision = '1b316f8d977d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   op.add_column('domain', sa.Column('sheet_id', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   op.drop_column('domain')
    # ### end Alembic commands ###
