"""Add lead_cost field

Revision ID: 792a607d5ceb
Revises: a09f89511ad6
Create Date: 2023-08-04 10:49:51.528062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '792a607d5ceb'
down_revision = 'a09f89511ad6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   op.add_column('domain', sa.Column('lead_cost', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('reset_token', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('reset_token_expiration', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('username', name='users_username_key')
    )
    op.create_table('processed_data',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('data', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='processed_data_pkey'),
    sa.UniqueConstraint('data', name='processed_data_data_key')
    )
    op.create_table('lead',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('label', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('firstname', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phone1', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ozip', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('dzip', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('dcity', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('dstate', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('movesize', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('movedte', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('conversion', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('validation', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sent_to_gronat', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sent_to_sheets', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='lead_pkey')
    )
    op.create_table('domain',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('label', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('domain', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('d_phone_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('send_to_leads_api', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('send_to_google_sheet', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('twilio_number_validation', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sms_texting', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='domain_pkey')
    )
    # ### end Alembic commands ###
