"""your message here

Revision ID: 8c39be55d297
Revises: 21495cb2698a
Create Date: 2023-09-07 13:54:27.628405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c39be55d297'
down_revision = '21495cb2698a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('domain', sa.Column('moverref', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('domain', sa.Column('moverref', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
